### ISSUE TITLE
Scrum master projeto C

### ISSUE THREAD

**Issue by rafaelcorsi** [Andre-Weber/Z01.1-Fury#23]
https://github.com/Andre-Weber/Z01.1-Fury/blob/a9d300b9b143f5137fe6ace36ca47b1029273999/Projetos/C-LogicaCombinacional/SCRUM_MASTER.json#L2

Favor preencher !

**Comment by rafaelcorsi** [comment]
Preciso dessa informação....

**Comment by andrekwr** [comment]
Feito, desculpe!
